# Generated by Django 5.0.6 on 2025-02-20 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegisterLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='profile_photos/')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100, null=True)),
                ('bio', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientPostProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the project', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the project')),
                ('category', models.CharField(choices=[('ai_developement', 'AI Development'), ('animation', 'Animation'), ('business_strategy', 'Business Strategy'), ('content_creation', 'Content Creation'), ('contract_drafting', 'Contract Drafting'), ('graphic_design', 'Graphic Design'), ('legal_consulting', 'Legal Consulting'), ('logo_design', 'Logo Design'), ('machine_learning', 'Machine Learning'), ('market_research', 'Market Research'), ('social_media_marketing', 'Social Media Marketing'), ('software_development', 'Software Development'), ('video_editing', 'Video Editing'), ('web_development', 'Web Development'), ('music_composition', 'Music Composition'), ('lyric_writting', 'Lyric Writing')], help_text='Project category', max_length=50)),
                ('budget', models.DecimalField(decimal_places=2, help_text='Project budget (fixed or hourly)', max_digits=20)),
                ('budget_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly')], help_text='Budget type', max_length=10)),
                ('deadline', models.DateField(help_text='Deadline for project completion')),
                ('skills_required', models.CharField(help_text='Skills required for the project', max_length=255)),
                ('attachments', models.FileField(blank=True, help_text='Project-related files', null=True, upload_to='project_attachments/')),
                ('photo', models.ImageField(blank=True, help_text='Project-related photo', null=True, upload_to='project_photos/')),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('intermediate', 'Intermediate Level'), ('expert', 'Expert Level')], help_text='Required experience level for freelancers', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when the project was posted')),
                ('status', models.CharField(max_length=10, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='client.clientregisterlogin')),
            ],
        ),
    ]
