# Generated by Django 5.0.6 on 2025-01-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpostproject',
            name='budget',
            field=models.DecimalField(decimal_places=2, help_text='Project budget (fixed or hourly)', max_digits=20),
        ),
    ]
