# Generated by Django 5.0.6 on 2025-01-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='ClientRegisterLogin',
        ),
    ]
