# Generated by Django 5.0.6 on 2025-01-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_client_clientregisterlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('categories', models.CharField(max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_type', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=255)),
                ('experience_level', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='project_attachments/')),
            ],
        ),
    ]
