# Generated by Django 5.0.6 on 2025-01-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_clientpostproject_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpostproject',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
