# Generated by Django 5.0.6 on 2025-01-15 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_postproject_delete_emailpassword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostProject',
            new_name='ClientPostProject',
        ),
    ]
