# Generated by Django 5.0.6 on 2025-01-15 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_rename_postproject_clientpostproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpostproject',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='client.clientregisterlogin'),
        ),
    ]
