# Generated by Django 5.0.6 on 2025-01-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_clientpostproject_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientregisterlogin',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
