# Generated by Django 5.0.6 on 2025-01-23 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('project_posted', 'Project Posted'), ('proposal_submitted', 'Proposal Submitted'), ('proposal_approved', 'Proposal Approved'), ('submission_received', 'Submission Received'), ('project_submitted', 'Project Submitted'), ('client_registered', 'Client Registered'), ('freelancer_registered', 'Freelancer Registered'), ('contact_message', 'Contact Message'), ('payment_received', 'Payment Received')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.adminuser')),
            ],
        ),
    ]
