# Generated by Django 5.0.6 on 2025-01-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
