# Generated by Django 5.0.6 on 2025-01-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_remove_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
