# Generated by Django 5.0.6 on 2025-01-15 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerregisterlogin',
            name='about_me',
        ),
    ]
