# Generated by Django 5.0.6 on 2025-01-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_remove_freelancerregisterlogin_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerregisterlogin',
            name='about_me',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
