# Generated by Django 5.0.6 on 2025-01-18 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_clientregisterlogin_location'),
        ('freelancer', '0003_freelancerregisterlogin_about_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(editable=False, max_length=255)),
                ('project_description', models.TextField(editable=False)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateField()),
                ('cover_letter', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='proposal_attachments/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.freelancerregisterlogin')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='client.clientpostproject')),
            ],
        ),
    ]
