# Generated by Django 5.0.6 on 2025-01-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0004_freelancerproposal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancerproposal',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='freelancerproposal',
            old_name='project_title',
            new_name='title',
        ),
    ]
