# Generated by Django 5.0.6 on 2025-01-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0005_rename_project_description_freelancerproposal_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreelancerProposal',
        ),
    ]
