# Generated by Django 5.0.6 on 2025-01-18 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_clientregisterlogin_location'),
        ('freelancer', '0006_delete_freelancerproposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(editable=False)),
                ('duration', models.CharField(choices=[('1_day', '1 Day'), ('2_days', '2 Days'), ('3_days', '3 Days'), ('4_days', '4 Days'), ('5_days', '5 Days'), ('7_days', '7 Days'), ('10_days', '10 Days'), ('15_days', '15 Days'), ('1_month', '1 Month'), ('2_month', '2 Months'), ('3_month', '3 Months')], max_length=20)),
                ('bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateField()),
                ('cover_letter', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.freelancerregisterlogin')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.clientpostproject')),
            ],
        ),
    ]
