# Generated by Django 5.0.6 on 2025-01-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0007_freelancerproposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerproposal',
            name='deadline',
        ),
        migrations.AlterField(
            model_name='freelancerproposal',
            name='duration',
            field=models.CharField(choices=[('1_day', '1 Day'), ('2_days', '2 Days'), ('3_days', '3 Days'), ('4_days', '4 Days'), ('5_days', '5 Days'), ('7_days', '7 Days'), ('10_days', '10 Days'), ('15_days', '15 Days'), ('1_month', '1 Month'), ('2_months', '2 Months'), ('3_months', '3 Months')], max_length=20),
        ),
    ]
