# Generated by Django 5.0.6 on 2025-01-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0008_remove_freelancerproposal_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerproposal',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
