# Generated by Django 5.0.6 on 2025-01-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0009_alter_freelancerproposal_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerproposal',
            name='description',
            field=models.TextField(editable=False, null=True),
        ),
    ]
