# Generated by Django 5.0.6 on 2025-01-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0010_alter_freelancerproposal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerproposal',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='freelancerproposal',
            name='cover_letter',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='freelancerproposal',
            name='duration',
            field=models.CharField(choices=[('1_day', '1 Day'), ('2_days', '2 Days'), ('3_days', '3 Days'), ('4_days', '4 Days'), ('5_days', '5 Days'), ('7_days', '7 Days'), ('10_days', '10 Days'), ('15_days', '15 Days'), ('1_month', '1 Month'), ('2_months', '2 Months'), ('3_months', '3 Months')], max_length=20, null=True),
        ),
    ]
