# Generated by Django 5.0.6 on 2025-01-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0012_alter_freelancerproposal_bid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreelancerProposal',
        ),
    ]
