# Generated by Django 5.0.6 on 2025-01-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0014_freelancerproposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerproposal',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
