# Generated by Django 5.0.6 on 2025-01-21 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0016_alter_freelancerproposal_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_status', models.CharField(max_length=15)),
                ('payment_status', models.CharField(max_length=15)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.freelancerproposal')),
            ],
        ),
    ]
