# Generated by Django 5.0.6 on 2025-01-21 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_clientregisterlogin_location'),
        ('freelancer', '0017_projectpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerproposal',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.clientregisterlogin'),
        ),
    ]
